---
title: 'R CASE STUDY 3: DATA VISUALIZATION IN R'
author: "shashvindu jha"
date: "28/06/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown





```{r}
setwd("D:\\download\\1.3 - R Case Studies (All 3 case studies for Foundation R)\\R case study 3 (Visualization)")
SalesData <- read.csv("SalesData.csv")
```

## Including Plots

```{r}
require(dplyr)
Region_Sales <-SalesData %>% group_by(Region) %>% summarise(TotalSales2015=sum(Sales2015),TotalSales2016=sum(Sales2016)) 
#install.packages("reshape2",dependencies = T)
require(reshape2)
Region_Sales1 <- melt(Region_Sales,id.vars = "Region", variable.name = "Year",value.name = "Sales")

require(ggplot2)
Plot_Region_Sales <- ggplot(data = Region_Sales1) + aes(x = Region, y = Sales, fill = Year) + 
                            geom_bar(stat = "identity", position = "Dodge") + 
                            geom_text(label = round(Region_Sales1$Sales,0),na.rm = F)+ 
                            scale_y_continuous()
```
```{r}
```
```{r}
```
```{r}
```
```{r}
```
```{r}
```
```{r}
```
```{r}
```
```{r}
```

```{r}
```
```{r}
```
```{r}
```
